### ISSUE TITLE
Logstash won't start after upgrading to 2.3.110

### ISSUE THREAD

**Issue by jaek79** [Security-Onion-Solutions/securityonion#7651]
Hello,

I have performed the version upgrade to 2.3.110 and started seeing the below issue. 
I could able to start other services but logstash won't start and hang at Wait_start status. 
I have included the below details.
Please if anyone could help I would greatly appreciate it. 

standalone 
2.3.110

error:
[CRITICAL] Rendering SLS 'base:logstash' failed: Jinja variable 'None' has no attribute 'items'
/var/cache/salt/minion/files/base/logstash/map.jinja(7):
---
[...]
{% set REDIS_NODES = [] %}
{% set mainint = salt['pillar.get']('host:mainint') %}
{% set localhostip = salt['grains.get']('ip_interfaces').get(mainint)[0] %}
{% if role in ['so-node', 'so-standalone', 'so-managersearch'] %}
  {% set node_data = salt['pillar.get']('logstash:nodes') %}
  {% for node_type, node_details in node_data.items() | sort %}    <======================
    {% if node_type in ['manager', 'managersearch', 'standalone', 'receiver' ] %}
      {% for hostname in node_data[node_type].keys() %}
        {% do REDIS_NODES.append({hostname:node_details[hostname].ip}) %}
      {% endfor %}
    {% endif %}
[...]
---
local:
    Data failed to compile:
----------
    Rendering SLS 'base:logstash' failed: Jinja variable 'None' has no attribute 'items'
/var/cache/salt/minion/files/base/logstash/map.jinja(7):
---
[...]
{% set REDIS_NODES = [] %}
{% set mainint = salt['pillar.get']('host:mainint') %}
{% set localhostip = salt['grains.get']('ip_interfaces').get(mainint)[0] %}
{% if role in ['so-node', 'so-standalone', 'so-managersearch'] %}
  {% set node_data = salt['pillar.get']('logstash:nodes') %}
  {% for node_type, node_details in node_data.items() | sort %}    <======================
    {% if node_type in ['manager', 'managersearch', 'standalone', 'receiver' ] %}
      {% for hostname in node_data[node_type].keys() %}
        {% do REDIS_NODES.append({hostname:node_details[hostname].ip}) %}
      {% endfor %}
    {% endif %}
[...]
---
